import type {
  ColorRefs,
  FlagModule,
  ScriptSettings,
  ScriptTemplate,
  TerminalTheme,
} from '../types/script';
import { DEPENDENCY_REGISTRY } from '../config/dependencies';
import { COLOR_TOKENS } from '../types/script';
import { boxedComment, colorize, frag, sectionRule } from './builder';

/**
 * ────────────────────────────────────────────────────────────────────────────
 *  OmniScript compiler engine
 * ────────────────────────────────────────────────────────────────────────────
 *  `compileBashScript` is a pure function — the same inputs always produce the
 *  same bytes, so the output can be snapshotted, diffed and unit tested.
 *
 *  Compilation pipeline:
 *    1. Shebang + option headers (safety flags)
 *    2. Color mapping block (theme -> ANSI variables)
 *    3. Runtime helpers + template preflight (dependency/root policy)
 *    4. Auto-documenting help menu (only the enabled modules)
 *    5. Clipboard utility (opt-in)
 *    6. Input argument evaluator (`case "$1" in` over active modules)
 *    7. Entrypoint
 */

export const DEFAULT_SETTINGS: ScriptSettings = {
  commandName: '',
  includeColor: true,
  failFastOnErrors: true,
  includeClipboard: false,
  verifyDependencies: true,
  includeTrace: false,
};

/** Map a free-form command name onto something safe for an executable. */
export function sanitizeCommandName(input: string, fallback: string): string {
  const cleaned = input
    .trim()
    .replace(/[^A-Za-z0-9._-]+/g, '-')
    .replace(/-{2,}/g, '-')
    .replace(/^[.-]+/, '')
    .replace(/[.-]+$/, '')
    .slice(0, 48);
  return cleaned.length > 0 ? cleaned : fallback;
}

/** `%` is the printf escape character — double it inside generated text. */
export function escapePrintf(text: string): string {
  return text.replace(/%/g, '%%');
}

/** `"-a | --active"` -> `"-a"`, used for the help example line. */
export function modulePrimaryPattern(flag: string): string {
  const first = flag.split('|')[0]?.trim() ?? '';
  return first.length > 0 ? first : flag.trim();
}

export function activeModulesOf(
  template: ScriptTemplate,
  activeModuleIds: ReadonlySet<string>,
): FlagModule[] {
  return template.modules.filter((module) => activeModuleIds.has(module.id));
}

/** Unique, sorted dependency set required by the currently enabled modules. */
export function collectRequiredDependencies(
  template: ScriptTemplate,
  activeModuleIds: ReadonlySet<string>,
): string[] {
  const deps: string[] = [];
  for (const module of activeModulesOf(template, activeModuleIds)) {
    for (const dep of module.requiredDependencies) {
      if (!deps.includes(dep)) deps.push(dep);
    }
  }
  return deps.sort();
}

/** Escape a string so it is safe inside a generated `"..."` bash literal. */
export function escapeBashDouble(text: string): string {
  return text
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\$/g, '\\$')
    .replace(/`/g, '\\`');
}

/**
 * The object handed to every `bashCaseBlock`. Values are shell *references*,
 * so modules stay theme agnostic while remaining valid `Record<string,string>`.
 */
export function buildColorRefs(): ColorRefs {
  return {
    NC: '${NC}',
    BOLD: '${BOLD}',
    MUTED: '${MUTED}',
    OK: '${OK}',
    WARN: '${WARN}',
    ERR: '${ERR}',
    INFO: '${INFO}',
    TITLE: '${TITLE}',
    VALUE: '${VALUE}',
  };
}

/* ── 1. Shebang + option headers ───────────────────────────────────────────── */

function renderHeader(
  template: ScriptTemplate,
  modules: FlagModule[],
  theme: TerminalTheme,
  commandName: string,
): string {
  return boxedComment([
    `OmniScript :: ${template.name}`,
    template.shortDescription,
    '',
    `Base template   : ${template.id}`,
    `Executable name : ${commandName}`,
    `Terminal theme  : ${theme.label} (${theme.id})`,
    `Active modules  : ${modules.length} of ${template.modules.length}`,
    'Generated by    : OmniScript — the ultimate Linux shell utility composer',
  ]);
}

function renderOptionHeaders(settings: ScriptSettings): string {
  const lines = [
    sectionRule('1. Runtime safety'),
    '#',
    '# $OMNISCRIPT_COMMAND_NAME overrides the trigger name printed in help text',
    '# and error messages — handy when the file is symlinked into /usr/local/bin.',
    '#',
  ];
  if (settings.failFastOnErrors) {
    lines.push(
      'set -euo pipefail   # exit on error, unset variable, or failed pipe stage',
      "IFS=$'\\n\\t'          # split on newlines/tabs only — never on spaces",
    );
  } else {
    lines.push(
      '# strict mode disabled: the script keeps going after individual failures',
      "IFS=$'\\n\\t'",
    );
  }
  if (settings.includeTrace) {
    lines.push('set -x              # verbose tracing (every command is echoed)');
  }
  return lines.join('\n');
}

/* ── 2. Color mapping ──────────────────────────────────────────────────────── */

function renderColorSection(theme: TerminalTheme, includeColor: boolean): string {
  const clear = COLOR_TOKENS.map((token) => `${token}=""`).join(' ');

  if (!includeColor) {
    return [
      sectionRule(`2. Color mapping :: ${theme.label} palette compiled out`),
      '#',
      '# Colors are disabled, but the variables still exist (empty) so that',
      '# `set -u` never trips on a colorized reference inside a module.',
      '#',
      clear,
    ].join('\n');
  }

  return [
    sectionRule(`2. Color mapping :: ${theme.label} palette`),
    '#',
    ...COLOR_TOKENS.map((token) => `${token}=$'${theme.ansi[token]}'`),
    '',
    '# Auto-degrade to plain text when stdout is not a terminal (pipe/cron/CI).',
    'if [ ! -t 1 ]; then',
    `  ${clear}`,
    'fi',
  ].join('\n');
}

/* ── 3. Runtime helpers + preflight ────────────────────────────────────────── */

/** Build the `case` arms of the generated dependency translation tables. */
function dependencyCases(field: 'probe' | 'package'): string[] {
  return Object.values(DEPENDENCY_REGISTRY)
    .filter((info) => info[field] !== info.id)
    .map((info) => `    ${info.id}) echo "${info[field]}" ;;`);
}

function renderRuntimeHelpers(
  modules: FlagModule[],
  dependencies: string[],
  settings: ScriptSettings,
): string {
  const depLoop = dependencies.length
    ? dependencies
        .map((dep) => `  require_dependency ${dep} || missing=$((missing + 1))`)
        .join('\n')
    : '  : # no external dependencies declared by the active modules';

  return [
    sectionRule('3. Runtime helpers'),
    '#',
    `# active modules     : ${modules.map((m) => m.id).join(', ') || 'none'}`,
    `# required packages  : ${dependencies.join(', ') || 'none — pure shell'}`,
    '#',
    '',
    'die() {',
    '  printf "%s✖%s %s\\n" "$ERR" "$NC" "$1" >&2',
    '  exit 1',
    '}',
    '',
    'have() {',
    '  command -v "$1" >/dev/null 2>&1',
    '}',
    '',
    'os_package_manager() {',
    '  if have apt-get; then echo "apt-get"',
    '  elif have dnf; then echo "dnf"',
    '  elif have yum; then echo "yum"',
    '  elif have pacman; then echo "pacman"',
    '  elif have zypper; then echo "zypper"',
    '  elif have apk; then echo "apk"',
    '  elif have brew; then echo "brew"',
    '  else echo ""',
    '  fi',
    '}',
    '',
    'install_hint() {',
    '  local pm',
    '  pm="$(os_package_manager)"',
    '  case "$pm" in',
    '    apt-get) echo "sudo apt-get install -y $1" ;;',
    '    dnf | yum) echo "sudo $pm install -y $1" ;;',
    '    pacman) echo "sudo pacman -S --noconfirm $1" ;;',
    '    zypper) echo "sudo zypper install -y $1" ;;',
    '    apk) echo "sudo apk add $1" ;;',
    '    brew) echo "brew install $1" ;;',
    '    *) echo "install $1 with your distribution package manager" ;;',
    '  esac',
    '}',
    '',
    '# Declared dependency -> executable that proves the package is installed.',
    '# Mirrors src/config/dependencies.ts, which avoids the classic',
    '# "command -v iproute2" mistake of probing a package name as a binary.',
    'dependency_probe() {',
    '  case "$1" in',
    ...dependencyCases('probe'),
    '    *) echo "$1" ;;',
    '  esac',
    '}',
    '',
    '# Declared dependency -> package name used in the install hint.',
    'dependency_package() {',
    '  case "$1" in',
    ...dependencyCases('package'),
    '    *) echo "$1" ;;',
    '  esac',
    '}',
    '',
    '# VERIFY_DEPENDENCIES=0 skips package enforcement (minimal images, CI).',
    'require_dependency() {',
    '  local declared="$1" probe',
    '  if [ "${VERIFY_DEPENDENCIES:-1}" -eq 0 ]; then return 0; fi',
    '  probe="$(dependency_probe "$declared")"',
    '  if have "$probe"; then return 0; fi',
    '  printf "%s✖ missing dependency:%s %s\\n" "$ERR" "$NC" "$declared" >&2',
    '  if [ "$probe" != "$declared" ]; then',
    '    printf "  %s↳%s the %s command is not available\\n" "$MUTED" "$NC" "$probe" >&2',
    '  fi',
    '  printf "  %s↳%s %s\\n" "$MUTED" "$NC" "$(install_hint "$(dependency_package "$declared")")" >&2',
    '  return 1',
    '}',
    '',
    'require_root() {',
    '  if [ "$(id -u)" -ne 0 ]; then',
    '    die "this command needs root — re-run with: sudo $SCRIPT_NAME"',
    '  fi',
    '}',
    '',
    'banner() {',
    '  printf "\\n%s▌ %s%s%s\\n" "$TITLE" "$1" "$BOLD" "$NC"',
    '}',
    '',
    'rule() {',
    '  printf "%s────────────────────────────%s\\n" "$MUTED" "$NC"',
    '}',
    '',
    'verify_dependencies() {',
    '  local missing=0',
    depLoop,
    '  if [ "$missing" -gt 0 ]; then',
    `    die "missing ${dependencies.length} declared package(s) — install them and retry"`,
    '  fi',
    '}',
    '',
    '# Runtime escape hatches:',
    '#   VERIFY_DEPENDENCIES=0|1   -> override the compiled dependency guard',
    'if [ "${OMNISCRIPT_DEBUG:-0}" = "1" ]; then set -x; fi',
    '',
    `VERIFY_DEPENDENCIES="\${VERIFY_DEPENDENCIES:-${settings.verifyDependencies ? 1 : 0}}"`,
  ].join('\n');
}

/* ── 4. Auto-generated help menu ───────────────────────────────────────────── */

function renderHelp(
  template: ScriptTemplate,
  modules: FlagModule[],
  commandName: string,
  dependencies: string[],
): string {
  const moduleLines = modules.map(
    (module) =>
      `  printf "  %s%-30s%s %s\\n" "$INFO" "${escapePrintf(module.flag)}" "$NC" "${escapePrintf(module.summary)}"`,
  );

  const example = modules.length
    ? `  printf "  %s%s %s%s\\n" "$VALUE" "${commandName}" "${escapePrintf(modulePrimaryPattern(modules[0]!.flag))}" "$NC"`
    : '  printf "  %s%s --help%s\\n" "$VALUE" "$SCRIPT_NAME" "$NC"';

  return [
    sectionRule('4. Auto-generated help menu'),
    '#',
    '# Rebuilt on every compile: it can only ever document enabled modules.',
    '',
    `SHORT_DESCRIPTION="${escapeBashDouble(template.shortDescription)}"`,
    '',
    'show_help() {',
    '  printf "\\n%s%s%s\\n" "$BOLD$TITLE" "$SCRIPT_NAME" "$NC"',
    '  printf " %s%s%s\\n" "$MUTED" "$SHORT_DESCRIPTION" "$NC"',
    '',
    '  printf "\\n%sUSAGE%s\\n" "$TITLE" "$NC"',
    '  printf "  %s <command> [arguments]\\n" "$SCRIPT_NAME"',
    '',
    '  printf "\\n%sCOMMANDS%s\\n" "$TITLE" "$NC"',
    ...moduleLines,
    '  printf "  %s%-30s%s %s\\n" "$INFO" "-h | --help" "$NC" "Show this help menu"',
    '',
    '  printf "\\n%sEXAMPLE%s\\n" "$TITLE" "$NC"',
    example,
    '',
    '  printf "\\n%sREQUIREMENTS%s\\n" "$TITLE" "$NC"',
    `  printf "  %s\\n" "${escapePrintf(dependencies.join(', ') || 'none — pure shell')}"`,
    '  printf "\\n"',
    '}',
  ].join('\n');
}

/* ── 5. Clipboard utility ──────────────────────────────────────────────────── */

function renderClipboard(): string {
  return [
    sectionRule('5. Universal clipboard utility'),
    '#',
    '# Wayland -> X11 -> macOS. Never breaks a pipeline: with no tool available',
    '# the payload is consumed silently so `set -euo pipefail` stays happy.',
    '',
    'copy_to_clipboard() {',
    '  if have wl-copy; then wl-copy',
    '  elif have xclip; then xclip -selection clipboard',
    '  elif have xsel; then xsel --clipboard --input',
    '  elif have pbcopy; then pbcopy',
    '  else',
    '    cat >/dev/null',
    '    printf "%s⚠ clipboard tool not found%s\\n" "$WARN" "$NC" >&2',
    '    printf "  %s↳%s %s\\n" "$MUTED" "$NC" "$(install_hint wl-clipboard)" >&2',
    '    return 0',
    '  fi',
    '}',
  ].join('\n');
}

/* ── 6. Input argument evaluator ───────────────────────────────────────────── */

function renderDispatch(modules: FlagModule[], colors: ColorRefs): string {
  const branches = modules.map((module) =>
    module
      .bashCaseBlock(colors)
      .replace(/^[\r\n]+/, '')
      .replace(/\s+$/, ''),
  );

  return [
    sectionRule('6. Input argument evaluator'),
    '#',
    '# Every enabled module contributes exactly one branch, in template order, so',
    '# a newly registered module becomes reachable with zero compiler changes.',
    '',
    'dispatch() {',
    '  case "${1:-}" in',
    '    "")',
    '      show_help',
    '      exit 0',
    '      ;;',
    '    -h | --help)',
    '      show_help',
    '      exit 0',
    '      ;;',
    ...(branches.length ? branches : ['    # no modules enabled — add some in OmniScript']),
    '    *)',
    '      printf "%s✖ unknown command:%s %s\\n" "$ERR" "$NC" "${1:-}" >&2',
    "      printf \"  run '%s --help' to list available commands\\n\" \"$SCRIPT_NAME\" >&2",
    '      exit 64',
    '      ;;',
    '  esac',
    '}',
  ].join('\n');
}

/* ── 7. Entrypoint ─────────────────────────────────────────────────────────── */

function renderEntrypoint(commandName: string): string {
  return frag(
    sectionRule('7. Entrypoint'),
    '',
    `SCRIPT_NAME="\${OMNISCRIPT_COMMAND_NAME:-${commandName}}"`,
    '',
    'main() {',
    '  preflight',
    '',
    '  # Help must never be gated behind a package install check.',
    '  case "${1:-}" in',
    '    "" | -h | --help)',
    '      dispatch "$@"',
    '      return 0',
    '      ;;',
    '  esac',
    '',
    '  verify_dependencies',
    '  dispatch "$@"',
    '}',
    '',
    'main "$@"',
  );
}

/* ── Public API ────────────────────────────────────────────────────────────── */

export function compileBashScript(
  template: ScriptTemplate,
  activeModuleIds: ReadonlySet<string>,
  settings: ScriptSettings,
  theme: TerminalTheme,
): string {
  const modules = activeModulesOf(template, activeModuleIds);
  const commandName = sanitizeCommandName(
    settings.commandName.trim() || template.defaultCommandName,
    template.defaultCommandName,
  );
  const dependencies = collectRequiredDependencies(template, activeModuleIds);

  const sections = [
    renderHeader(template, modules, theme, commandName),
    renderOptionHeaders(settings),
    renderColorSection(theme, settings.includeColor),
    renderRuntimeHelpers(modules, dependencies, settings),
    colorize(template.baseSystemChecks.trim(), buildColorRefs()),
    renderHelp(template, modules, commandName, dependencies),
    settings.includeClipboard ? renderClipboard() : '',
    renderDispatch(modules, buildColorRefs()),
    renderEntrypoint(commandName),
  ];

  return `${sections.filter((section) => section.length > 0).join('\n\n')}\n`;
}

/** Suggested file name for the download action. */
export function scriptFileName(
  template: ScriptTemplate,
  settings: ScriptSettings,
): string {
  const name = sanitizeCommandName(
    settings.commandName.trim() || template.defaultCommandName,
    template.defaultCommandName,
  );
  return `${name}.sh`;
}
